#
# Copyright (C) 2022 web1n
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for iWiFi
LUCI_DEPENDS:=+iwifi
LUCI_PKGARCH:=all
PKG_VERSION:=1
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
